server:
  port: 9080
  servlet:
    context-path: /payment/api
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    openfeign:
      client:
        config:
          userService:
            url: http://localhost:8080/users/api
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

currency:
  fetch:
    cron: "0 * * * * ?"
  exchange:
    url: https://api.exchangeratesapi.io
    access-key: 9a0774e234d2bf1c16fdd7a2f6e84850
    actual-currency: EUR,USD,RUB,BYN

redis:
  port: 6379
  host: localhost
  channel:
    exchange_rates: currency

resilience4j:
  retry:
    instances:
      exchangeRatesRetry:
        maxAttempts: 10
        waitDuration: 3s
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - feign.FeignException

open-exchange-rates:
  url: https://openexchangerates.org/api/latest.json
  key: c976ce71ebb74adb83e52ed7245797a8

logging:
  level:
    root: info
